name: Lint

on:
  pull_request:
    paths:
      - '**.py'
      - '.github/workflows/lint.yml'

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: flake8 Lint
      uses: py-actions/flake8@v2
      with:
        max-line-length: "88"
        ignore: "E402"

    - name: isort lint
      uses: isort/isort-action@v1