name: tests

on:
  pull_request:
    paths:
      - '**.py'
      - '.github/workflows/tests.yml'
      - 'requirements.txt'

jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        cache: pip

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: python3 -m pytest
      env:
        PYTHONPATH: ${{ github.workspace }}/src
