name: tests

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install torch

    - name: Run tests
      run: python3 -m pytest
      env:
        PYTHONPATH: ${{ github.workspace }}/src
